### PR TITLE
Added a feature for moving tabs to new window

### PR DESCRIPTION
**Pull request by samharad**

### CODE REVIEW

**Comment by mohnish** [comment]
hi @samharad, thanks for taking time and implementing this. I'm sorry I haven't gotten to this PR yet. I have been busy with other things and I failed to check the PR. I apologize for the delay.

I was going through https://github.com/mohnish/rearrange-tabs/issues/26 and I think the designated keyboard shortcuts, (up and down) arrow keys fit well with moving tabs to the first and last positions. Can you think of any other shortcuts that'd fit well with the current use case? Also, IIRC, Chrome only allows extensions to use 4 shortcuts and no more than that. I'm not sure if that has changed, but, it'd be helpful if you could make sure we comply with that. Once again, thank you for your effort. I really appreciate it.

**Comment by TomasJuocepis** [comment]
> Also, IIRC, Chrome only allows extensions to use 4 shortcuts and no more than that. I'm not sure if that has changed, but, it'd be helpful if you could make sure we comply with that.

The limit of 4 shortcuts only applies to default/suggested shortcuts (in the manifest). There is no limit on the number of commands that can be declared without a suggested shortcut but configurable to have a shortcut by the user.

**Comment by samharad** [comment]
Hi @mohnish, thanks for commenting, and no worries about the delay. I added the functionality for my own convenience, and thought others might benefit too if this is thought to be a worthwhile addition to the extension. 

> I was going through #26 and I think the designated keyboard shortcuts, (up and down) arrow keys fit well with moving tabs to the first and last positions. Can you think of any other shortcuts that'd fit well with the current use case?

I agree that Up/Down suit #26. I've changed the new-window shortcut to Space.

Thanks for the clarification, @TomasJuocepis:
> The limit of 4 shortcuts only applies to default/suggested shortcuts (in the manifest).

I've left the default shortcut in the manifest, but perhaps it makes more sense to have the Up/Down functionality as default, and leave the new-window functionality for the user to configure.

I've updated the README to reflect the new feature.

**Comment by mohnish** [comment]
@samharad This looks great. 👌
Also, the `README` update looks good. I'll go over the changes once I'm back home. Thanks for contributing.

**Comment by samharad** [comment]
Okay @mohnish, I believe the conflicts are resolved and everything is functioning well.

**Comment by Jon-Schneider** [comment]
@mohnish Could you please merge this?

**Review by akirataguchi115 — CHANGES_REQUESTED** [review]
Maybe rebase 3.0 and then we'll see how the extension works with your changes?

**Comment by mohnish** [comment]
@akirataguchi115 Since @samharad put in their time and effort into this PR, I'd like to have it as part of the codebase. I will branch off of `main` and merge this PR into that branch (so that their effort could be recorded in the history of the repo). I can then fix the code and make it work with the new rewrite. I think that's more convenient even for Sam.

**Pull request merged**
